### ISSUE TITLE
Templates • Heat pump plant

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#3605]
This ticket is to track the development of a template for heat pump plants to be contributed to `Buildings.Templates`.
The proposed coverage of system options is described in "Options & Scope" at https://docs.google.com/spreadsheets/d/1FOG5dpEpXkTbxO7uS9zrNPpvkU24VGNtgRZq6xW-cMk/edit?usp=sharing

**TODO**

- [x] Validate system options that are covered
- [x] Develop SOO in English and control diagrams
- [x] Implement SOO in CDL
- [x] Implement equipment model
- [x] Perform closed-loop validation based on realistic load profiles
- [ ] Develop Python scripts to automate tests for all plant configurations

**Feature branch**
- [`issue3605_template_HP_plant`](https://github.com/lbl-srg/modelica-buildings/tree/issue3605_template_HP_plant)
  └ Dependencies: 
    - `issue3746_fullClassNames`: This is a workaround for a failure in class name lookup with OCT.
    - *(`IBPSASync_issue1576_heatPumpModelIntegration`: Dependency previously added but removed with 2d963a8658 due to the limitations and issues described in https://docs.google.com/document/d/130SBzYK3YHHSzFvr5FyW_WOXmNGoXKzUJ3Wahq1rx9U/edit#heading=h.6z2iztspwv65)*

**Requirements**
- See https://lbl-srg.github.io/modelica-buildings-templates/guide, but also note the remarks below
- Use a configuration data record as introduced for the VAV templates via #3508
- Use a top-level parameter `viewDiagramAll` to toggle the visibility of all components and connection lines in the diagram layer: if `viewDiagramAll=false` the diagram view should correspond to the control diagram
- Use the test workflow as introduced for the VAV templates via #3528

**Remarks**
- Integration into ctrl-flow is not yet planned. The documentation of the SOO will be included as HTML documentation within class annotations. 
- Using only the HTML documentation to generate the SOO document (as opposed to using a master Word document as with the VAV templates) would require the following developments:
    - ctrlf-flow: exporting Modelica classes with the appropriate class modifications → See the original specification at https://lbl-srg.github.io/ctrl-flow/requirements.html#class-manipulation-and-workflow
    - modelica-json: generating a Word document based on the documentation in class annotations → See the original specification at https://obc.lbl.gov/specification/sequenceDocumentation.html#exporting-the-control-logic-from-a-cdl-model

**Comment by AntoineGautier** [comment]
Closed as completed. The test scripts will be developed under #3808.
